name: Test-Release
run-name: Release ${{ github.ref_name }}
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_call:
  workflow_dispatch:

jobs:
  promote:
    name: Promote
    runs-on: ubuntu-latest
    steps:
      - name: Promote
        id: promote
        shell: bash
        run: |
          echo "Promote"

  envs_to_release:
    name: Get environments to release
    needs: promote
    runs-on: ubuntu-latest
#    outputs:
#      environments: ${{ steps.set-env.outputs.environments }}
#    steps:
#      - name: Get environments
#        id: set-environments
#        run: |
#          echo "environments={\"environments\":[{\"name\":\"dev\",\"config\":\"Debug\"},{\"name\":\"pre\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"include\":[{\"name\":\"dev\",\"config\":\"Debug\"},{\"name\":\"pre\",\"config\":\"Release\"}]}"

  execute-upgrades:
    name: Execute upgrades
    needs:
      - promote
      - envs_to_release
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.envs_to_release.outputs.matrix) }}
    steps:
      - name: Upgrade environment
        uses: ./.github/workflows/upgrade.yml
        with:
          environment: ${{ matrix.name }}
          release-name: ${{ github.ref_name }}