name: Test-Release
run-name: Release ${{ github.ref_name }}
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_call:
  workflow_dispatch:

jobs:
  promote:
    name: Promote
    runs-on: ubuntu-latest
    steps:
      - name: Promote
        id: promote
        shell: bash
        run: |
          echo "Promote"

  envs_to_release:
    name: Get environments to release
    needs: promote
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        matrix='{ "include": [ {"name": "dev", "config": "Debug"}, {"name": "pre", "config": "Release"} ] }'
        echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  execute-upgrades:
    name: Execute upgrades
    needs:
      - promote
      - envs_to_release
    strategy:
      matrix: ${{ fromJson(needs.envs_to_release.outputs.matrix) }}
    uses: ./.github/workflows/upgrade.yml
    secrets: inherit
    with:
      environment: ${{ matrix.name }}
      release-name: ${{ github.ref_name }}