name: Test-Release
run-name: Release ${{ github.ref_name }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_call:
  workflow_dispatch:

jobs:
  envs_to_release:
    name: Get environments to release
    needs: promote
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        matrix='{ "include": [ {"name": "dev", "config": "Debug"}, {"name": "pre", "config": "Release"} ] }'
        echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  promote:
    name: Promote
    needs:
      - envs_to_release
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.envs_to_release.outputs.matrix) }}
    uses: ./.github/workflows/promote.yml
    with:
      environment: ${{ matrix.name }}

  execute-upgrades:
    name: Execute upgrades
    needs:
      - envs_to_release
      - promote
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.envs_to_release.outputs.matrix) }}
    uses: ./.github/workflows/upgrade.yml
    secrets: inherit
    with:
      environment: ${{ matrix.name }}
      release-name: ${{ github.ref_name }}